---
pagetitle: "Trawl Biodiversity Metrics for Landings Comparison"
author: "Jerelle Jesse"
output:
  html_document: 
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

## Diveristy metrics
```{r setup, include=FALSE}
library(here)
library(ggplot2)
library(dplyr)
data<-read.csv(here("Data/MaineDMR_Trawl_Survey_Catch_Data_2021-05-14.csv"))

```

### Species richness
```{r echo=FALSE, message=FALSE}
richness<-group_by(data, Year,Season)%>%
  summarise(richness=length(unique(COMMON_NAME)))

ggplot()+ geom_line(data=richness, aes(Year, richness))+facet_grid(rows = vars(Season))

richness<-group_by(data, Year)%>%
  summarise(richness=length(unique(COMMON_NAME)))

rich<-ggplot()+ geom_line(data=subset(richness,Year>2005), aes(Year, richness))+ theme_classic()+ ylab(expression(paste("Species\nRichness")))+theme(plot.margin = margin(10, 10, 10, 20))

rich
```

### Shannon-Weiner diversity

```{r echo=FALSE, message=FALSE}
shannon<-group_by(data, Year,Season,COMMON_NAME)%>%
  mutate(species_total=sum(Expanded_Weight_kg, na.rm=TRUE))%>%
  group_by(Year, Season)%>%
  mutate(total=sum(species_total), prop=(species_total/total))%>%
  summarise(shannon=-1*(sum(prop*log(prop),na.rm=TRUE)))

ggplot()+geom_line(data=shannon, aes(Year, shannon))+ 
  facet_grid(rows=vars(Season))

shannon<-group_by(data, Year,COMMON_NAME)%>%
  mutate(species_total=sum(Expanded_Weight_kg, na.rm=TRUE))%>%
  group_by(Year)%>%
  mutate(total=sum(species_total),prop=(species_total/total))%>%
  summarise(shannon=-1*(sum(prop*log(prop),na.rm=TRUE)))

diversity<-ggplot()+geom_line(data=subset(shannon,Year>2005), aes(Year, shannon))+theme_classic()+ ylab(expression(paste("Shannon-Weiner\nDiversity")))+theme(plot.margin = margin(10, 10, 10, 20))

diversity

```

### Simpson's diversity and evenness
```{r echo=FALSE, message=FALSE}
simpson<-group_by(data, Year, Season, COMMON_NAME)%>%
  mutate(species_total=sum(Expanded_Weight_kg, na.rm=TRUE))%>%
  group_by(Year, Season)%>%
  mutate(richness=length(unique(COMMON_NAME)))%>%
  mutate(total=sum(species_total))%>%
  mutate(prop=(species_total/total))%>%
  summarise(simpsonD=1/(sum(prop^2)), simpsonE=simpsonD*(1/richness))
# this code is not working properly, very high simpson's d and e??

ggplot()+geom_line(data=simpson, aes(Year, simpsonE))+
  facet_grid(rows=vars(Season))

simpson<-group_by(data, Year,COMMON_NAME)%>%
  summarise(species_total=sum(Expanded_Weight_kg, na.rm=TRUE))%>% #aggregate to get yearly species totals
  group_by(Year)%>%
  mutate(richness=length(unique(COMMON_NAME)))%>%
  mutate(total=sum(species_total))%>%
  mutate(prop=(species_total/total))%>%
  summarise(simpsonD=1/(sum(prop^2)),simpsonE=simpsonD*(1/richness))
   
ggplot()+geom_line(data=simpson, aes(Year, simpsonD))+theme_classic()

evenness<-ggplot()+geom_line(data=subset(simpson,Year>2005), aes(Year, simpsonE))+theme_classic()+ ylab(expression(paste("Simpson's\nEvenness")))+theme(plot.margin = margin(10, 10, 10, 20))

evenness

```

### Average taxinomic distinctness
```{r echo=FALSE, message=FALSE}
library(taxize)
library(purrr)
library(mgcv)

data2<-read.csv(here("Data/common_scientific_convert.csv"))%>%
  distinct(COMMON_NAME, .keep_all=TRUE)

data2<-left_join(data,data2, by="COMMON_NAME")

species <- filter(data2,!is.na(SCIENTIFIC_NAME))%>%
  rename(Species=SCIENTIFIC_NAME)
  #add scientific name for taxonomic distinctness

na<-filter(data2, is.na(SCIENTIFIC_NAME))%>%
  distinct(COMMON_NAME)

diff_species<-as.vector(unique(species$Species))
tax <- classification(diff_species, db = 'itis') 
info <- matrix(NA)
expand <- matrix(NA)
specific <- matrix(NA, nrow = length(diff_species), ncol=6)


for (i in 1:length(tax)){
info <- tax[[i]][c('name','rank')]
expand <- info[info$rank == 'phylum'| info$rank == 'class'| info$rank == 'order' | info$rank == 'family' | info$rank == 'genus' | info$rank == 'species',]
specific[i,] <- as.vector(expand$name)

}
colnames(specific) <- c("Phylum", "Class", "Order", "Family", "Genus", "Species")
phylo<-as.data.frame(specific)

merge<-left_join(species,phylo, by="Species")
  
data_tax<-data%>%
  full_join(merge)%>%
  filter(!is.na(Species))

data_tax_groups<-group_by(data_tax, Year,Species)%>%
  summarise(catch=sum(Expanded_Weight_kg, na.rm=TRUE))%>%
  mutate(indicator=cur_group_id())

hauls <- unique(data_tax_groups$indicator)   
N_hauls <- length(hauls) # number of hauls
N_species <- NULL #N species
sub_species <- NULL # N_species-1
total <- NULL  #xixj
numerator <- NULL #wijxixj
x_y <- matrix(NA, nrow = 6, ncol = 6) 
x <- NULL
y <- NULL
ident <- NULL
weight <- NULL #wij
count <- NULL
total_weight <- NULL
mean_weight <- NULL
weight_var <- NULL
delta <- NULL
delta_star <- NULL
delta_plus <- NULL
delta_var <- NULL
weight_var <- NULL

for (j in 1:N_hauls) {  
diff_hauls <- data_tax[which(data_tax_groups$indicator == j),] #subset unique hauls/functional groups
N_species[j] <- length(unique(diff_hauls$Species))# count the number of unique species in each haul (denominator)
sub_species[j] <- N_species[j]-1
diff <- unique(as.vector(diff_hauls$Species)) # name of each unique species 
combos <- combn(diff, 2) # create combinations of each species/haul (for weight calc)

phylo <- as.matrix(subset(diff_hauls, select = c(Phylum,Class,Order,Family,Genus, Species))) # extract phylogenetic information only
unique_phylo <- uniquecombs(phylo) # subset by unique species information
unique_phylo <- as.data.frame(unique_phylo)

total <- NULL  # reset the length for each haul because they will be different
weight <- NULL # reset  

for (i in 1:ncol(combos)) { # for each unique combination count the number of each species 
  total[i] <- sum(diff_hauls$Species == combos[1,i]) * sum(diff_hauls$Species == combos[2,i]) #empty vector is always length 210
  #total[i] <- diff_hauls[diff_hauls[,22] == combos[1,i],9] * diff_hauls[diff_hauls[,22] == combos[2,i],9]
  x <- unique_phylo[unique_phylo$Species == combos[1,i],]
  y <- unique_phylo[unique_phylo$Species == combos[2,i],]
  x_y <- rbind(x,y)
  
  for (k in 1:ncol(x_y)){ # for each combination calculate the weight value 
    ident[k] <- identical(as.vector(x_y[1,k]), as.vector(x_y[2,k])) # determine how much of phylogenetic information is the same
    weight[i] <- sum(ident == "FALSE") # vector of weights
    #mean_weight[i] <- mean(weight) #rep(mean(weight),length(weight))
    numerator[j] <- sum(total*weight) 
    count[j] <- sum(total)
    mean_weight[j] <- mean(weight)
    total_weight[j] <- sum(weight)
    weight_var[j] <- sum((weight- mean(weight))^2) 
  }
  delta <- (2*numerator)/(N_species*sub_species)
  delta_star <- numerator/(count)
  delta_plus <- (2*total_weight)/(N_species*sub_species)
  delta_var <- (2*weight_var)/(N_species*sub_species) #double check that this equation is correct
}
}
years<-2006:2020
delta<-as.data.frame(delta[1:15]) # taxonomic diversity
delta_star<-as.data.frame(delta_star[1:15]) # taxonomic distinctness
delta_plus<-as.data.frame(delta_plus[1:15]) # average taxonomic distinctness
delta_var<-as.data.frame(delta_var[1:15]) # variation in taxonomic distinctness

d<-bind_cols(years,delta, delta_star,delta_plus,delta_var)
colnames(d)<-c("Year", "delta", "delta_star", "delta_plus","delta_var")

#write.csv(d, here("Data/tax_metrics.csv"))

tax.distinct<-ggplot()+geom_line(data=subset(d,Year>2005), aes(Year, delta_plus))+theme_classic()+ylab(expression(paste("Average\nTaxinomic\nDistinctness")))+theme(plot.margin = margin(10, 10, 10, 25))
                                                                                     
tax.distinct
```

Combo plot
```{r echo=FALSE, message=FALSE}
library(reshape2)
library(gridExtra)

all_metrics<-full_join(richness,shannon, by="Year")%>%
  full_join(simpson)%>%
  full_join(d)

all_melt<-melt(all_metrics, id="Year")

ggplot()+geom_line(data=all_melt, aes(Year,value))+facet_grid(rows = vars(variable), scales="free")+theme_bw()

grid.arrange(rich, diversity, evenness,tax.distinct, nrow=4)

```
