---
pagetitle: "Objective 4: Fishery Landings"
author: "Jerelle Jesse"
output:
  html_document: 
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(here)
library(rmarkdown)
library(ggplot2)
library(ggthemes)
```
# Objective 4: Fishery Landings 

## Data
* Maine DMR landings data
* 2006-2020

<br>
```{r echo=FALSE, message=FALSE}
landings<- read.csv(here("Data/MaineDMR_Modern_Landings_Data_All.csv"))

landings_sum<-select(landings, year, county, species, weight, value)%>%
              group_by(year, county, species)%>%
              summarise(weight=sum(weight), value=sum(value))

landings_06<-read.csv(here("Data/MaineDMR_2006_2007_Landings.csv"))

landings_total<-bind_rows(landings_06, landings_sum)
paged_table(landings_total)


```

<br>

### County
```{r echo=FALSE, message=FALSE}

county<-group_by(landings_total, county, year)%>%
      summarise(total_weight=sum(weight, na.rm=TRUE))
paged_table(county)

#plots
p1<-ggplot(data=county, aes(x=year, y=total_weight, color=county))+
  geom_line()+ theme_classic()
p1

```

<br>

### Species
```{r echo=FALSE, message=FALSE}
species<-group_by(landings_total,species, year)%>%
      summarise(total_weight=sum(weight, na.rm=TRUE))
paged_table(species)

```

<br>

#### Top 10 species
```{r echo=FALSE, message=FALSE}
order<-group_by(species, species)%>%
  summarise(avg_weight=mean(total_weight, na.rm=TRUE))%>%
  arrange(desc(avg_weight))

top_10<-order[1:10,1]
species_top<-inner_join(species, top_10)
  
p2<-ggplot(data=species_top, aes(x=year, y=total_weight, color=species))+
  geom_line()+ theme_classic()
p2
```

<br>


## Diveristy metrics

### Species richness
```{r echo=FALSE, message=FALSE}
richness<-group_by(landings_total, county, year)%>%
  summarise(richness=length(unique(species)))

ggplot()+ geom_line(data=richness, aes(year, richness))+
  facet_grid(rows=vars(county))

richness<-group_by(landings_total, year)%>%
  summarise(richness=length(unique(species)))

rich<-ggplot()+ geom_line(data=richness, aes(year, richness))+ theme_classic()+ ylab(expression(paste("Species\nRichness")))+theme(plot.margin = margin(10, 10, 10, 20))

```

### Shannon-Weiner diversity
Based on weight not abundance of species
```{r echo=FALSE, message=FALSE}
shannon<-group_by(landings_total, year,county)%>%
  mutate(total=sum(weight), prop=weight/total)%>%
  summarise(shannon=-1*(sum(prop*log(prop))))

ggplot()+geom_line(data=shannon, aes(year, shannon))+
  facet_grid(rows=vars(county))

shannon<-group_by(landings_total, year,species)%>%
  mutate(species_total=sum(weight))%>%
  group_by(year)%>%
  mutate(total=sum(species_total),prop=species_total/total)%>%
  summarise(shannon=-1*(sum(prop*log(prop))))

diversity<-ggplot()+geom_line(data=shannon, aes(year, shannon))+theme_classic()+ ylab(expression(paste("Shannon-Weiner\nDiversity")))+theme(plot.margin = margin(10, 10, 10, 20))

```

### Simpson's diversity and evenness
```{r echo=FALSE, message=FALSE}
simpson<-group_by(landings_total, year, county)%>%
  mutate(total=sum(weight), prop=weight/total)%>%
  summarise(simpson=1/(sum(prop^2)) )

ggplot()+geom_line(data=simpson, aes(year, simpson))+
  facet_grid(rows=vars(county))

simpson<-group_by(landings_total, year,species)%>%
  summarise(species_total=sum(weight))%>% #aggregate counties to get yearly species totals for all of Maine
  group_by(year)%>%
  mutate(richness=length(unique(species)))%>%
  mutate(total=sum(species_total))%>%
  mutate(prop=species_total/total)%>%
  summarise(simpsonD=1/(sum(prop^2)),simpsonE=simpsonD*(1/richness))
   
ggplot()+geom_line(data=simpson, aes(year, simpsonD))+theme_classic()

evenness<-ggplot()+geom_line(data=simpson, aes(year, simpsonE))+theme_classic()+ ylab(expression(paste("Simpson's\nEvenness")))+theme(plot.margin = margin(10, 10, 10, 20))


```

### Average taxinomic distinctness
```{r echo=FALSE, message=FALSE}
library(taxize)
library(purrr)
library(mgcv)

species<-read.csv(here("Data/species_landings.csv"))%>%
  filter(scientific.name!="")%>%
  filter(scientific.name!="Fucus vesiculosus")%>%
  rename(common_name=species, Species=scientific.name)
  

diff_species<-as.vector(unique(species$Species))
tax <- classification(diff_species, db = 'itis') 
info <- matrix(NA)
expand <- matrix(NA)
specific <- matrix(NA, nrow = length(diff_species), ncol=6)


for (i in 1:length(tax)){
info <- tax[[i]][c('name','rank')]
expand <- info[info$rank == 'phylum'| info$rank == 'class'| info$rank == 'order' | info$rank == 'family' | info$rank == 'genus' | info$rank == 'species',]
specific[i,] <- as.vector(expand$name)

}
colnames(specific) <- c("Phylum", "Class", "Order", "Family", "Genus", "Species")
phylo<-as.data.frame(specific)

merge<-left_join(species,phylo, by="Species")
  
landings_tax<-rename(landings_total, common_name=species)%>%
  full_join(merge)%>%
  filter(!is.na(Species))

landings_tax_groups<-group_by(landings_tax, year,Species)%>%
  summarise(weight=sum(weight))%>%
  mutate(indicator=cur_group_id())

hauls <- unique(landings_tax_groups$indicator)   
N_hauls <- length(hauls) # number of hauls
N_species <- NULL #N species
sub_species <- NULL # N_species-1
total <- NULL  #xixj
numerator <- NULL #wijxixj
x_y <- matrix(NA, nrow = 6, ncol = 6) 
x <- NULL
y <- NULL
ident <- NULL
weight <- NULL #wij
count <- NULL
total_weight <- NULL
mean_weight <- NULL
weight_var <- NULL
delta <- NULL
delta_star <- NULL
delta_plus <- NULL
delta_var <- NULL
weight_var <- NULL

for (j in 1:N_hauls) {  
diff_hauls <- landings_tax[which(landings_tax_groups$indicator == j),] #subset unique hauls/functional groups
N_species[j] <- length(unique(diff_hauls$Species))# count the number of unique species in each haul (denominator)
sub_species[j] <- N_species[j]-1
diff <- unique(as.vector(diff_hauls$Species)) # name of each unique species 
combos <- combn(diff, 2) # create combinations of each species/haul (for weight calc)

phylo <- as.matrix(subset(diff_hauls, select = c(Phylum,Class,Order,Family,Genus, Species))) # extract phylogenetic information only
unique_phylo <- uniquecombs(phylo) # subset by unique species information
unique_phylo <- as.data.frame(unique_phylo)

total <- NULL  # reset the length for each haul because they will be different
weight <- NULL # reset  

for (i in 1:ncol(combos)) { # for each unique combination count the number of each species 
  total[i] <- sum(diff_hauls$Species == combos[1,i]) * sum(diff_hauls$Species == combos[2,i]) #empty vector is always length 210
  #total[i] <- diff_hauls[diff_hauls[,22] == combos[1,i],9] * diff_hauls[diff_hauls[,22] == combos[2,i],9]
  x <- unique_phylo[unique_phylo$Species == combos[1,i],]
  y <- unique_phylo[unique_phylo$Species == combos[2,i],]
  x_y <- rbind(x,y)
  
  for (k in 1:ncol(x_y)){ # for each combination calculate the weight value 
    ident[k] <- identical(as.vector(x_y[1,k]), as.vector(x_y[2,k])) # determine how much of phylogenetic information is the same
    weight[i] <- sum(ident == "FALSE") # vector of weights
    #mean_weight[i] <- mean(weight) #rep(mean(weight),length(weight))
    numerator[j] <- sum(total*weight) 
    count[j] <- sum(total)
    mean_weight[j] <- mean(weight)
    total_weight[j] <- sum(weight)
    weight_var[j] <- sum((weight- mean(weight))^2) 
  }
  delta <- (2*numerator)/(N_species*sub_species)
  delta_star <- numerator/(count)
  delta_plus <- (2*total_weight)/(N_species*sub_species)
  delta_var <- (2*weight_var)/(N_species*sub_species) #double check that this equation is correct
}
}
years<-2006:2020
delta<-as.data.frame(delta[1:15]) # taxonomic diversity
delta_star<-as.data.frame(delta_star[1:15]) # taxonomic distinctness
delta_plus<-as.data.frame(delta_plus[1:15]) # average taxonomic distinctness
delta_var<-as.data.frame(delta_var[1:15]) # variation in taxonomic distinctness

d<-bind_cols(years,delta, delta_star,delta_plus,delta_var)
colnames(d)<-c("year", "delta", "delta_star", "delta_plus","delta_var")

write.csv(d, here("Data/tax_metrics.csv"))

tax.distinct<-ggplot()+geom_line(data=d, aes(year, delta_plus))+theme_classic()+ylab(expression(paste("Average\nTaxinomic\nDistinctness")))+theme(plot.margin = margin(10, 10, 10, 25))
                                                                                     

```

Combo plot
```{r}
library(reshape2)
library(gridExtra)

all_metrics<-full_join(richness,shannon, by="year")%>%
  full_join(simpson)%>%
  full_join(d)

all_melt<-melt(all_metrics, id="year")

ggplot()+geom_line(data=all_melt, aes(year,value))+facet_grid(rows = vars(variable), scales="free")+theme_bw()

grid.arrange(rich, diversity, evenness,tax.distinct, nrow=4)

```


## Functional Groups
```{r echo=FALSE, message=FALSE}
groups<-read.csv(here("Data/species_groups.csv"))
landings_groups<-mutate(landings_total,COMMON_NAME=tolower(species))%>%
  left_join(groups, by="COMMON_NAME")

landings_groups$functional_group[landings_groups$functional_group==""]<-"undefined"
landings_groups$functional_group[is.na(landings_groups$functional_group)]<-"undefined"

#average weight of each group/ year
year_group<-group_by(landings_groups,year,county, functional_group)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))%>%
  group_by(year, functional_group)%>%
  summarise(average_weight=mean(weight_avg, na.rm=TRUE))

#proportion of groups per county/year
year_group_prop<-group_by(landings_groups,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, functional_group)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))
  
ggplot(year_group)+
  geom_line(aes(x=year, y=average_weight, color=functional_group))+
  scale_color_colorblind()+ theme_classic()

ggplot(year_group_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=functional_group), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()+ ylab("Proportion of biomass (kg)")+theme(text=element_text(size=18))


```

### Benthivore
```{r echo=FALSE, message=FALSE}
benthivore<-filter(landings_groups, functional_group=="benthivore")
group_benthivore<-group_by(benthivore,year, COMMON_NAME)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))

benthivore_prop<-group_by(benthivore,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, COMMON_NAME)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))

ggplot(group_benthivore)+
  geom_line(aes(x=year, y=weight_avg, color=COMMON_NAME))+
  scale_color_colorblind()+ theme_classic()

ggplot(benthivore_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=COMMON_NAME), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()


```
<br>

### Benthos
```{r echo=FALSE, message=FALSE}
benthos<-filter(landings_groups, functional_group=="benthos")
group_benthos<-group_by(benthos,year, COMMON_NAME)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))

benthos_prop<-group_by(benthos,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, COMMON_NAME)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))

ggplot(group_benthos)+
  geom_line(aes(x=year, y=weight_avg, color=COMMON_NAME))+
  scale_color_colorblind()+ theme_classic()

ggplot(benthos_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=COMMON_NAME), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()
```
<br>

### Piscivore
```{r echo=FALSE, message=FALSE}
piscivore<-filter(landings_groups, functional_group=="piscivore")

order<-group_by(piscivore, COMMON_NAME)%>%
  summarise(avg_weight=mean(weight, na.rm=TRUE))%>%
  arrange(desc(avg_weight))

top_10<-order[1:8,1]
piscivore_top<-inner_join(piscivore, top_10)

group_piscivore<-group_by(piscivore_top,year, COMMON_NAME)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))

piscivore_prop<-group_by(piscivore_top,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, COMMON_NAME)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))

ggplot(group_piscivore)+
  geom_line(aes(x=year, y=weight_avg, color=COMMON_NAME))+
  scale_color_colorblind()+ theme_classic()

ggplot(piscivore_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=COMMON_NAME), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()
```
<br>

### Planktivore
```{r echo=FALSE, message=FALSE}
planktivore<-filter(landings_groups, functional_group=="planktivore")
group_planktivore<-group_by(planktivore,year, COMMON_NAME)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))

planktivore_prop<-group_by(planktivore,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, COMMON_NAME)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))

ggplot(group_planktivore)+
  geom_line(aes(x=year, y=weight_avg, color=COMMON_NAME))+
  scale_color_colorblind()+ theme_classic()

ggplot(planktivore_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=COMMON_NAME), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()
```
<br>

### Undefined
```{r echo=FALSE, message=FALSE}
undefined<-filter(landings_groups, functional_group=="undefined")

order<-group_by(undefined, COMMON_NAME)%>%
  summarise(avg_weight=mean(weight, na.rm=TRUE))%>%
  arrange(desc(avg_weight))

top_10<-order[1:8,1]
undefined_top<-inner_join(undefined, top_10) 

group_undefined<-group_by(undefined_top,year, COMMON_NAME)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))

undefined_prop<-group_by(undefined_top,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, COMMON_NAME)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))

ggplot(group_undefined)+
  geom_line(aes(x=year, y=weight_avg, color=COMMON_NAME))+
  scale_color_colorblind()+ theme_classic()

ggplot(undefined_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=COMMON_NAME), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()
```


