---
pagetitle: "Objective 4: Fishery Landings"
author: "Jerelle Jesse"
output:
  html_document: 
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(here)
library(rmarkdown)
library(ggplot2)
library(ggthemes)
```
# Objective 4: Fishery Landings 

## Data
* Maine DMR landings data
* 2006-2020

<br>
```{r echo=FALSE, message=FALSE}
landings<- read.csv(here("Data/MaineDMR_Modern_Landings_Data_All.csv"))

landings_sum<-select(landings, year, county, species, weight, value)%>%
              group_by(year, county, species)%>%
              summarise(weight=sum(weight), value=sum(value))

landings_06<-read.csv(here("Data/MaineDMR_2006_2007_Landings.csv"))

landings_total<-bind_rows(landings_06, landings_sum)
paged_table(landings_total)


```

<br>

### County
```{r echo=FALSE, message=FALSE}

county<-group_by(landings_total, county, year)%>%
      summarise(total_weight=sum(weight, na.rm=TRUE))
paged_table(county)

#plots
p1<-ggplot(data=county, aes(x=year, y=total_weight, color=county))+
  geom_line()+ theme_classic()
p1

```

<br>

### Species
```{r echo=FALSE, message=FALSE}
species<-group_by(landings_total,species, year)%>%
      summarise(total_weight=sum(weight, na.rm=TRUE))
paged_table(species)

```

<br>

#### Top 10 species
```{r echo=FALSE, message=FALSE}
order<-group_by(species, species)%>%
  summarise(avg_weight=mean(total_weight, na.rm=TRUE))%>%
  arrange(desc(avg_weight))

top_10<-order[1:10,1]
species_top<-inner_join(species, top_10)
  
p2<-ggplot(data=species_top, aes(x=year, y=total_weight, color=species))+
  geom_line()+ theme_classic()
p2
```

<br>

## Functional Groups
```{r echo=FALSE, message=FALSE}
groups<-read.csv(here("Data/species_groups.csv"))
landings_groups<-mutate(landings_total,COMMON_NAME=tolower(species))%>%
  left_join(groups, by="COMMON_NAME")

landings_groups$functional_group[landings_groups$functional_group==""]<-"undefined"
landings_groups$functional_group[is.na(landings_groups$functional_group)]<-"undefined"

#average weight of each group/ year
year_group<-group_by(landings_groups,year,county, functional_group)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))%>%
  group_by(year, functional_group)%>%
  summarise(average_weight=mean(weight_avg, na.rm=TRUE))

#proportion of groups per county/year
year_group_prop<-group_by(landings_groups,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, functional_group)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))
  
ggplot(year_group)+
  geom_line(aes(x=year, y=average_weight, color=functional_group))+
  scale_color_colorblind()+ theme_classic()

ggplot(year_group_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=functional_group), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()


```

### Benthivore
```{r echo=FALSE, message=FALSE}
benthivore<-filter(landings_groups, functional_group=="benthivore")
group_benthivore<-group_by(benthivore,year, COMMON_NAME)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))

benthivore_prop<-group_by(benthivore,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, COMMON_NAME)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))

ggplot(group_benthivore)+
  geom_line(aes(x=year, y=weight_avg, color=COMMON_NAME))+
  scale_color_colorblind()+ theme_classic()

ggplot(benthivore_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=COMMON_NAME), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()


```
<br>

### Benthos
```{r echo=FALSE, message=FALSE}
benthos<-filter(landings_groups, functional_group=="benthos")
group_benthos<-group_by(benthos,year, COMMON_NAME)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))

benthos_prop<-group_by(benthos,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, COMMON_NAME)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))

ggplot(group_benthos)+
  geom_line(aes(x=year, y=weight_avg, color=COMMON_NAME))+
  scale_color_colorblind()+ theme_classic()

ggplot(benthos_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=COMMON_NAME), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()
```
<br>

### Piscivore
```{r echo=FALSE, message=FALSE}
piscivore<-filter(landings_groups, functional_group=="piscivore")

order<-group_by(piscivore, COMMON_NAME)%>%
  summarise(avg_weight=mean(weight, na.rm=TRUE))%>%
  arrange(desc(avg_weight))

top_10<-order[1:8,1]
piscivore_top<-inner_join(piscivore, top_10)

group_piscivore<-group_by(piscivore_top,year, COMMON_NAME)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))

piscivore_prop<-group_by(piscivore_top,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, COMMON_NAME)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))

ggplot(group_piscivore)+
  geom_line(aes(x=year, y=weight_avg, color=COMMON_NAME))+
  scale_color_colorblind()+ theme_classic()

ggplot(piscivore_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=COMMON_NAME), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()
```
<br>

### Planktivore
```{r echo=FALSE, message=FALSE}
planktivore<-filter(landings_groups, functional_group=="planktivore")
group_planktivore<-group_by(planktivore,year, COMMON_NAME)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))

planktivore_prop<-group_by(planktivore,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, COMMON_NAME)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))

ggplot(group_planktivore)+
  geom_line(aes(x=year, y=weight_avg, color=COMMON_NAME))+
  scale_color_colorblind()+ theme_classic()

ggplot(planktivore_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=COMMON_NAME), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()
```
<br>

### Undefined
```{r echo=FALSE, message=FALSE}
undefined<-filter(landings_groups, functional_group=="undefined")

order<-group_by(undefined, COMMON_NAME)%>%
  summarise(avg_weight=mean(weight, na.rm=TRUE))%>%
  arrange(desc(avg_weight))

top_10<-order[1:8,1]
undefined_top<-inner_join(undefined, top_10)

group_undefined<-group_by(undefined_top,year, COMMON_NAME)%>%
 summarise(weight_avg=mean(weight, na.rm=TRUE))

undefined_prop<-group_by(undefined_top,year,county)%>%
 mutate(weight_total=sum(weight))%>%
  mutate(prop=weight/weight_total)%>%
  group_by(year, COMMON_NAME)%>%
  summarise(mean_prop=mean(prop, na.rm=TRUE))

ggplot(group_undefined)+
  geom_line(aes(x=year, y=weight_avg, color=COMMON_NAME))+
  scale_color_colorblind()+ theme_classic()

ggplot(undefined_prop)+
  geom_bar(aes(x=year, y=mean_prop, fill=COMMON_NAME), position="fill", stat = "identity")+
  scale_fill_colorblind(name="Functional Group")+ theme_classic()
```

